#!/bin/sh

if [ $# -ne 1 ] || [ -z "$1" ]
then
    echo -e "USAGE: $0 BinNumber\nConvert binary number to decimal number" >&2
    exit 1
fi

mult=1
number=$1

if expr match "$number" "^-" > /dev/null;
then
    number=`echo "$number" | sed 's/^-\(.*\)$/\1/'`
    mult=-1
fi

if expr match "$number" "^[0-1]*$" > /dev/null;
then
    result=$((2#$number))
    echo "bin2dec($1)=$(($result * $mult))"
else
    echo "Error" >&2
    exit 1
fi
exit 0
