#!/bin/sh

if [ $# -ne 1 ]
then
    echo -e "USAGE: $0 n\nDisplay n first primary number" >&2
    exit 1
fi

if expr match "$1" "^[0-9]*$" > /dev/null
then
    i=0
else
    echo "ERROR" >&2
    exit 1
fi

if [ $1 -lt 0 ]
then
    echo "ERROR" >&2
    exit 1
fi

i=$1


j=0
number=2
str=""

while [ $j -lt $i ]
do
    div=2
    while [ $div -le $number ]
    do
	if [ `expr "$number" % "$div"` -eq 0 ]
	then
	    break
	fi
	div=$(($div + 1))
    done
    if [ $div -eq $number ]
    then
	if [ $(($j + 1)) -eq $i ]
	then
	    str="$str$number"
	else
	    str="$str$number "
	fi
	j=$((j + 1))
    fi
    number=$(($number + 1))
done

if [ $1 -gt 0 ]
then
    echo $str
fi
exit 0
